### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'scope')

### ISSUE THREAD

**Issue by mokone91** [KnodesCommunity/typedoc-plugins#130]
HI, getting next error with latest version of 'monorepo-readme' package
```TypeDoc exiting with unexpected error:
TypeError: Cannot read properties of undefined (reading 'scope')
    at MarkdownToSummary.processFromString (/Users/eldar/xxx/node_modules/.pnpm/@knodes+typedoc-pluginutils@0.23.0_typedoc@0.23.8/node_modules/@knodes/typedoc-pluginutils/dist/markdown-to-summary.js:59:35)
    at PageEvent.pageEvent.template (/Users/eldar/xxx/node_modules/.pnpm/@knodes+typedoc-plugin-monorepo-readmes@0.23.0_typedoc@0.23.8/node_modules/@knodes/typedoc-plugin-monorepo-readmes/dist/plugin.js:75:57)
    at defaultLayout xx(/Users/eldar/x/node_modules/.pnpm/typedoc@0.23.8_typescript@4.7.4/node_modules/typedoc/dist/lib/output/themes/default/layouts/default.js:29:23)
    at DefaultThemeRenderContext.defaultLayout (/Users/eldar/xxx/node_modules/.pnpm/typedoc@0.23.8_typescript@4.7.4/node_modules/typedoc/dist/lib/output/themes/default/DefaultThemeRenderContext.js:32:22)
    at DefaultTheme.defaultLayoutTemplate (/Users/eldar/xxx/node_modules/.pnpm/typedoc@0.23.8_typescript@4.7.4/node_modules/typedoc/dist/lib/output/themes/default/DefaultTheme.js:30:53)
    at DefaultTheme.render (/Users/eldar/xxx/node_modules/.pnpm/typedoc@0.23.8_typescript@4.7.4/node_modules/typedoc/dist/lib/output/themes/default/DefaultTheme.js:175:37)
    at Renderer.renderDocument (/Users/eldar/xxx/node_modules/.pnpm/typedoc@0.23.8_typescript@4.7.4/node_modules/typedoc/dist/lib/output/renderer.js:169:40)
    at /Users/eldar/xxx/node_modules/.pnpm/typedoc@0.23.8_typescript@4.7.4/node_modules/typedoc/dist/lib/output/renderer.js:148:22
    at Array.forEach (<anonymous>)
    at Renderer.render (/Users/eldar/xxx/node_modules/.pnpm/typedoc@0.23.8_typescript@4.7.4/node_modules/typedoc/dist/lib/output/renderer.js:146:25)
```

**Comment by mokone91** [comment]
Nice! thank you very much!

**Comment by GerkinDev** [comment]
Do you have an accessible link where I can look at your configuration in order to diagnose the problem more closely and create a non-regression test?

**Comment by mokone91** [comment]
unfortunately I cant share the link, here is my config
```
module.exports = {
  name: 'Sdk',
  readme: 'README.md',
  entryPointStrategy: 'packages',
  out: './docs',
  includes: ['./packages'],
  entryPoints: [
    './packages/*',
  ],
  excludePrivate: true,
  excludeProtected: true,
  cleanOutputDir: true,
  hideGenerator: true,
  includeVersion: false,
  customCss: './theme/main.css',
  exclude: [
    './packages/demo-app',
    '**/node_modules/**',
    '**/docs/**',
    '**/*.spec.ts',
  ],
};
```
```
"@knodes/typedoc-plugin-monorepo-readmes":"^0.23.0",
"typedoc-plugin-missing-exports": "0.23.0",
"typedoc": "^0.23.8"
```

**Comment by GerkinDev** [comment]
Well, I hope v0.23.1 fixes it !

**Comment by mokone91** [comment]
It works now! thanks!
