### ISSUE TITLE
Getting "repo.getLineNumberAnchor is not a function" after typedoc update

### ISSUE THREAD

**Issue by mokone91** [KnodesCommunity/typedoc-plugins#220]
### Plugin

@knodes/typedoc-plugin-monorepo-readmes

### Typedoc plugin(s) version(s)

^0.23.1

### Typedoc version

0.23.18

### Describe the problem

```

TypeDoc exiting with unexpected error:
TypeError: repo.getLineNumberAnchor is not a function
    at Object.createSourceReference (/Users/eldar/WebstormProjects/or-sdk-next/node_modules/.pnpm/@knodes+typedoc-pluginutils@0.23.1_typedoc@0.23.18/node_modules/@knodes/typedoc-pluginutils/dist/utils/reflection-source.js:49:32)
    at MonorepoReadmePlugin._modifyModuleIndexPage (/Users/eldar/WebstormProjects/or-sdk-next/node_modules/.pnpm/@knodes+typedoc-plugin-monorepo-readmes@0.23.1_typedoc@0.23.18/node_modules/@knodes/typedoc-plugin-monorepo-readmes/dist/plugin.js:61:68)
    at Renderer.<anonymous> (/Users/eldar/WebstormProjects/or-sdk-next/node_modules/.pnpm/@knodes+typedoc-plugin-monorepo-readmes@0.23.1_typedoc@0.23.18/node_modules/@knodes/typedoc-plugin-monorepo-readmes/dist/plugin.js:32:30)
    at triggerEvents (/Users/eldar/WebstormProjects/or-sdk-next/node_modules/.pnpm/typedoc@0.23.18_typescript@4.8.4/node_modules/typedoc/dist/lib/utils/events.js:191:43)
    at triggerApi (/Users/eldar/WebstormProjects/or-sdk-next/node_modules/.pnpm/typedoc@0.23.18_typescript@4.8.4/node_modules/typedoc/dist/lib/utils/events.js:167:13)
    at eventsApi (/Users/eldar/WebstormProjects/or-sdk-next/node_modules/.pnpm/typedoc@0.23.18_typescript@4.8.4/node_modules/typedoc/dist/lib/utils/events.js:60:18)
    at Renderer.trigger (/Users/eldar/WebstormProjects/or-sdk-next/node_modules/.pnpm/typedoc@0.23.18_typescript@4.8.4/node_modules/typedoc/dist/lib/utils/events.js:389:13)
    at Renderer.renderDocument (/Users/eldar/WebstormProjects/or-sdk-next/node_modules/.pnpm/typedoc@0.23.18_typescript@4.8.4/node_modules/typedoc/dist/lib/output/renderer.js:151:14)
    at /Users/eldar/WebstormProjects/or-sdk-next/node_modules/.pnpm/typedoc@0.23.18_typescript@4.8.4/node_modules/typedoc/dist/lib/output/renderer.js:135:22
    at Array.forEach (<anonymous>)
```

### What did you expected ?

Expecting no errors 

UPD:
 typedoc@0.23.16 - still works
 typedoc@0.23.17 - broken

**Comment by GerkinDev** [comment]
Yes indeed. I saw this method was modified in their changelog.

**Comment by GerkinDev** [comment]
Truth is, the next update is kind of stuck because I'm trying to preserve backward compatibility with the current version of the plugin, in order to follow semver notation for 0.x.x versions. And I would gain SO MUCH work time by dropping this version behavior entierly & focus only on the new behavior.

I was hoping typedoc would release a 0.24.0 version soon so that I can legitimately do breaking changes....

**Comment by mokone91** [comment]
possible its not relevant after https://github.com/TypeStrong/typedoc/issues/2065

**Comment by GerkinDev** [comment]
The readme stuff will be dropped anyway, but other features are still relevant.

**Comment by mokone91** [comment]
Im also use @knodes/typedoc-plugin-pages for adding changelog pages to packages, it works fine with latest typedoc

**Comment by souljorje** [comment]
@mokone91 hey! I also get this error right now and can't get why did you decide to close it?

**Comment by mokone91** [comment]
Hi! because 'readmes' feature added to typdeoc core and this plugin can be disabled

**Comment by souljorje** [comment]
@mokone91 ah, thanks a lot!

**Comment by adrienboulle** [comment]
@mokone91 not sure to understand
The error comes from this file https://github.com/KnodesCommunity/typedoc-plugins/blob/main/packages/pluginutils/src/utils/reflection-source.ts#L48
function `getLineNumberAnchor` no longer exists but is used by this plugin

**Comment by souljorje** [comment]
@adrienboulle this plugin is not needed anymore, since it's functionality became native in jsdoc since this release [TypeStrong/typedoc@v0.23.16 (release)](https://github.com/TypeStrong/typedoc/releases/tag/v0.23.16):
> In packages mode, readme files will now be automatically included if present, https://github.com/TypeStrong/typedoc/issues/2065.

**Comment by adrienboulle** [comment]
The errors not only occurs in  `@knodes/plugin-monorepo-readmes` but also in `@knodes/typedoc-plugin-pages`:

![image](https://user-images.githubusercontent.com/14262895/207809342-d5434efb-989d-481b-bf3e-68462c6eedf4.png)

**Comment by souljorje** [comment]
@adrienboulle 🤷‍♂️ try to instal; latest typedoc & @knodes/typedoc-plugin-pages

**Comment by adrienboulle** [comment]
that's what I did oc ;)

**Comment by adrienboulle** [comment]
@souljorje [this function](https://github.com/KnodesCommunity/typedoc-plugins/blob/main/packages/plugin-pages/src/output/theme/default-pages-renderer.tsx#L188) call on main branche calls the [utils function](https://github.com/KnodesCommunity/typedoc-plugins/blob/main/packages/pluginutils/src/utils/reflection-source.ts#L42) that make this [function call](https://github.com/KnodesCommunity/typedoc-plugins/blob/main/packages/pluginutils/src/utils/reflection-source.ts#L48) that does not exist

**Comment by GerkinDev** [comment]
Yeah sry about that. Unfortunately, I'm super busy right now, but a new version will hopefully be released soon. It's almost done.
